@url = http://localhost:5000/api/users

POST {{url}} HTTP/1.1
content-type: application/json

{
    "name": "mollie",
    "email": "mollie@gmail.com",
    "password": "mollie123"
}

###

POST {{url}}/login HTTP/1.1
content-type: application/json

{
    "email": "dave@gmail.com",
    "password": "dave123"
}

###

GET {{url}}/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTVhNzgyYmE2ODAyMzVlNzgzZDQ2ZCIsImVtYWlsIjoiZGF2ZUBnbWFpbC5jb20iLCJpYXQiOjE2NzE4MDg0OTksImV4cCI6MTY3NDQwMDQ5OX0.tosZ5h5b-VDATq1y_7nfFBcjXiVM39lWrcsOhg4MFr8